server:
  port: 9002

spring:
  application:
    name: PROJECT-SERVICE


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  dashboard:
    proxyStreamAllowList: "*"
